# Generated by Django 3.1.3 on 2020-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameImage', models.CharField(max_length=140, null=True)),
                ('uploadedImage', models.ImageField(null=True, upload_to='Upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
